name: yapayzekamobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  geocoding: ^2.2.1
  permission_handler: ^12.0.0+1
  flutter_riverpod: ^2.3.6
  http: ^1.3.0
  dio: ^5.4.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: 3.3.1
  go_router: ^13.0.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300